server:
  port: 8080

spring:
  jackson:
    serialization:
      indent_output: true

app:
  jwt:
    # 기본 Base64 secret (예시). 운영에서는 환경변수 JWT_SECRET로 덮어쓰기 권장
    secret: ${JWT_SECRET:VGhpcy1pcy1hLXN1cGVyLXNlY3JldC1zZWVkLWF0LWxlYXN0LTMyLWNoYXJzLWxvbmc=}
    ttlSeconds: ${JWT_TTL_SECONDS:900}

